#!r6rs

;;; Copyright © Marc Nieper-Wißkirchen (2023).

(rnrs base)
(rnrs unicode)
(rnrs bytevectors)
(rnrs lists)
(rnrs sorting)
(rnrs control)
(rnrs records syntactic)
(rnrs records procedural)
(rnrs records inspection)
(rnrs exceptions)
(rnrs conditions)
(rnrs io ports)
(rnrs io simple)
(rnrs files)
(rnrs programs)
(rnrs arithmetic fixnums)
(rnrs arithmetic flonums)
(rnrs arithmetic bitwise)
(rnrs hashtables)
(rnrs syntax-case)
(rnrs enums)
(rnrs)
(rnrs mutable-pairs)
(rnrs mutable-strings)
(rnrs r5rs)
(scheme-libraries with-implicit)
(scheme-libraries define-who)
